"""The interface for the client module"""
from typing import OrderedDict, Any
import asyncio

class Client:
    commands: list
    command_cache: OrderedDict[str, Any]
    event_cache: OrderedDict[str, Any]
    client_events: OrderedDict[str, Any]
    _token: str
    _app_id: str
    heartbeat_interval: int # miliseconds
    initial_heartbeat: int # heartbeat * rand(0->1)
    websocket: Any
    intents: int
    def __init__(self, token, intents, app_id, commands=None) -> None: ...
    def __call__(self, *args: Any, **kwds: Any) -> Any: ...
    def push(self, command) -> None: ...
    def push(self, commands) -> None: ...
    def on(self, event, callback) -> None: ...
    def connect(self) -> bool: ...
    def disconnect() -> bool: ...
    def register(self) -> bool: ...
    async def _startup(self, websocketUrl) -> bool:
    async def _loop(self) -> None:
    async def _heartbeatLoop(self) -> None: ...
