"""The interface for the client module"""
from typing import OrderedDict, Any


class Client:
    commands: OrderedDict[str, Any]
    discord_event_cache: OrderedDict[str, Any]
    client_events: OrderedDict[str, Any]
    _token: str
    heartbeat_interval: int # miliseconds 
    initial_heartbeat: int # heartbeat * rand(0->1)
    def __init__(self, token, intents) -> None: ...
    def __init__(self, token, intents, commands) -> None: ...
    def __call__(self, *args: Any, **kwds: Any) -> Any: ...
    def push(self, command) -> None: ...
    def push(self, commands) -> None: ...
    def on(self, event, callback) -> None: ...
    def connect() -> bool: ...
    def disconnect() -> bool: ...
    def register() -> bool: ...

