# For more information, see:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
# Add entries for npm, nuget, etc. if needed.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Every weekday
      interval: "daily"